DROP TABLE INSTALL
CASCADE CONSTRAINTS;

drop SEQUENCE INSTALL_SEQ;

CREATE SEQUENCE INSTALL_SEQ
START WITH 70000
INCREMENT BY 1
MAXVALUE 79999
NOCYCLE;

CREATE TABLE INSTALL(
	ins_index NUMBER(6) PRIMARY KEY,
	pur_index NUMBER(6) NOT NULL,
	ins_date  DATE  NULL,
	comp_date DATE  NULL,
	mgr_index NUMBER(6)  NULL,
	ins_state NUMBER(1)  NOT NULL
);

ALTER TABLE INSTALL
ADD CONSTRAINTS FK_INSTALL_pur_index_purchase FOREIGN KEY(pur_index)
REFERENCES purchase(pur_index);

ALTER TABLE INSTALL
ADD CONSTRAINTS FK_INSTALL_mgr_index_purchase FOREIGN KEY(mgr_index)
REFERENCES managerMember(mgr_index);